### PR TITLE
fix(tui-prompts): full-width character input in non-multiline prompt (#93)

### LINKED ISSUE #93: tui-prompts: incorrect cursor position with full-width characters
In the `text` example of tui-prompts, I entered full-width CJK characters (  ほげほげ  ) into the Username prompt. Pressing the Left key repeatedly to move to the start of the input text, the cursor only moves as far as the position shown in the screenshot:

Image

The leftmost position of the cursor should be over the first input character.

As I looked at the code relating to this recently, I would be happy to try submitting a fix.

### PR DESCRIPTION
**Pull request by 2910000**
Fixes #93
 
Here I have:

- added full-width character support for a non-multiline prompt
- removed tests  marked "FIXME" that failed after the changes
- amended the values of one failing test not marked "FIXME" - values appear incorrect from the context
- added a few tests for full-width character support
    - line wrapping with full-width characters is not working, so some tests are ignored

### CODE REVIEW

File: tui-prompts/src/prompt.rs [hunk 1]
```diff
@@ -196,6 +197,15 @@ pub trait State {
         }
         *self.position_mut() = self.position().saturating_add(1);
     }
+
+    /// The character width of the stored value up to the position pos.
+    fn width_to_pos(&self, pos: usize) -> usize {
+        self.value()
+            .chars()
+            .take(pos)
+            .map(|x| x.width_cjk().expect("cannot handle control characters"))
```
Comment (joshka) [inline tui-prompts/src/prompt.rs:206]: Why width_cjk here as opposed to just width?

Comment (joshka) [inline tui-prompts/src/prompt.rs:206]: Can we make this return 0 for control chars instead of panicking?

File: tui-prompts/src/text_prompt.rs [hunk 2]
```diff
@@ -88,7 +89,7 @@ impl<'a> StatefulWidget for TextPrompt<'a> {
         let width = area.width as usize;
         let height = area.height as usize;
         let value = self.render_style.render(state);
-        let value_length = value.chars().count();
+        let value_length: usize = value.width_cjk();
```
Comment (joshka) [inline tui-prompts/src/text_prompt.rs:92]:
```suggestion
        let value_width = value.width_cjk();
```

Also, this is only used once below, so perhaps just inline it?

File: tui-prompts/src/text_prompt.rs [hunk 3]
```diff
@@ -97,11 +98,16 @@ impl<'a> StatefulWidget for TextPrompt<'a> {
             " › ".cyan().dim(),
             Span::raw(value),
         ]);
-        let prompt_length = line.width() - value_length;
+        let prompt_length: usize = line
+            .iter()
+            .map(|x| x.content.to_string().width_cjk())
+            .sum::<usize>()
+            - value_length;
```
Comment (joshka) [inline tui-prompts/src/text_prompt.rs:105]: Looking at this, I wonder if this is worth pushing up into Ratatui core itself (e.g. `impl UnicodeWidthStr for Line`)? and then you'd be able to call `width_cjk()` directly on `Line`.

**Review by joshka — COMMENTED** [review]
I'm not super familiar with the differences between calling width() and width_cjk() here and why you'd choose one vs the other. Can you explain that a little?

File: tui-prompts/src/prompt.rs (hunk 1 above)
Comment (2910000) [reply tui-prompts/src/prompt.rs:206]: Ah I misread the docs.  I'll change these to use width

File: tui-prompts/src/text_prompt.rs (hunk 3 above)
Comment (2910000) [reply tui-prompts/src/text_prompt.rs:105]: I didn't realise that `Line` width() returns unicode width! And I think it's fine to use width instead of width_cjk so I'll change this back

**Comment by 2910000** [comment]
Here are notes on my most recent commit, correcting my misunderstandings from the previous commit:

- `width()` vs `width_cjk()`: should use `width()` here
    - for unicode characters with ambiguous width, `width()` uses the narrow form of the character, while `width_cjk()` uses the wide form. Using the wide form makes sense in a context with all CJK characters, because it would be weird to have a single narrow character in a text composed entirely of wide characters. In other contexts, [it is typical to use the narrow form](https://www.unicode.org/reports/tr11/#Ambiguous). In this case, it should be assumed that a prompt is being used for mixed character input

- the Ratatui `width()` functions behave correctly here
    - the `width()` method on `Line` finds the sum of the `width()`s of its `Span`s, and the `width()` method on `Span` returns unicode-width, so it's fine to use the Ratatui object widths here

**Comment by joshka** [comment]
Apologies on the delay on this one. Getting it over the line now with a couple of small fixes.
